services:
  - type: web
    name: gantt-dispatch-api
    env: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DB_ENGINE
        value: azure
      - key: PYTHON_VERSION
        value: 3.11.11